# Generated by Django 4.2.5 on 2023-10-06 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunevault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vault',
            name='description',
            field=models.TextField(default='this is the vault description'),
        ),
        migrations.AddField(
            model_name='vault',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vault',
            name='genres',
            field=models.TextField(default='here are the genres'),
        ),
        migrations.AddField(
            model_name='vault',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vault',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vault',
            name='spotifyimg',
            field=models.ImageField(default='unknown_vault.jpg', upload_to='vault_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
