# Generated by Django 4.2.1 on 2023-10-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunevault', '0002_profile_followers_vault_description_vault_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='vtype',
            field=models.TextField(default='artist', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='media/default_profile.jpg', upload_to='media/profile_image'),
        ),
    ]
