# Generated by Django 4.2.5 on 2023-10-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunevault', '0003_vault_type_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='authors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='external_url',
            field=models.TextField(default='https://open.spotify.com/', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vault',
            name='type',
            field=models.TextField(default='vault'),
        ),
    ]
