# Generated by Django 4.2.1 on 2023-11-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunevault', '0003_vault_vtype_alter_profile_profileimg'),
        ('tunevault', '0004_vault_authors_vault_external_url_alter_vault_type'),
    ]

    operations = [
    ]
